pipeline:
  build:
    image: reactioncommerce/base:v2.0.0
    commands:
      - go get
      - go build
      - go test
    notify:
      email:
        recipients:
          - curranabell@gmail.com
  publish:
    docker:
      username: curranabell
      password: drz400sm
      email: curranabell@gmail.com
      repo: curranabell/reaction-nmp
